### ISSUE TITLE
Adding Support for sci-float

### ISSUE THREAD

**Issue by shtse8** [krowinski/bcmath-extended#12]
Reference: https://stackoverflow.com/questions/21902817/convert-float-to-plain-string-representation

At the moment, we can't put sci-float val into arg.
Hoping to support it by adding the reference function to parsing sci-float first.

```php
	private function convertFloat($floatAsString)
	{
		$norm = strval(floatval($floatAsString));

		if (($e = strrchr($norm, 'E')) === false) {
			return $norm;
		}

		return number_format($norm, -intval(substr($e, 1)), '.', '');
	}
```

**Comment by krowinski** [comment]
@shtse8 checkout branch  #14

**Comment by krowinski** [comment]
added in 2.0.0-pre tag
