### ISSUE TITLE
Scientific notation regex

### ISSUE THREAD

**Issue by TheLevti** [krowinski/bcmath-extended#18]
> Please provide the following details.

* *Operating System*: Ubuntu 16.04.4 LTS
* *PHP Version*: 7.2.4
* *php-mysql-replication Version*: 5.6.*

> Steps required to reproduce the problem.

1. Have a html `<input type="number" />` field
2. Enter a scientific notation number that does not use `+` or `-` in the exponent part (valid format). e.g. `3.456e11`.
3. Send it to a php script that reads this string
4. Try to use `BC::convertScientificNotationToString(...)` on it.

> Expected Result.
* `"345600000000"`

> Actual Result.
*  `"3.45611"`

The problem is that `convertScientificNotationToString(int|string|float $number)` uses an uncomplete regex to test for a scientific notation. Please check the formal [php documentation](http://php.net/manual/en/language.types.float.php). It states:

```
LNUM [0-9]+
DNUM ([0-9]*[\.]{LNUM}) | ({LNUM}[\.][0-9]*)
EXPONENT_DNUM [+-]?(({LNUM} | {DNUM}) [eE][+-]? {LNUM})
```

1. The beginning of a number can also have an optional + sign `[+-]?`
2. The exponent part has an optional + or - sign `[+-]?`

**Comment by krowinski** [comment]
Tx for info fixed in 2.0.1
