### ISSUE TITLE
Idea: this project should add the existed bc methods

### ISSUE THREAD

**Issue by shtse8** [krowinski/bcmath-extended#2]
I like this project very much and it adds lots of missing methods from BC.
but the built-in bc is procedural style. and this project is using static OOP.
we still need to use bcadd/bcsub/bcmul/... in procedural style, while for max/min/avg we can use static OOP style. So I would like to suggest adding add/sub/mul/,,, those existing methods in this project. and let this project be more powerful.

**Comment by krowinski** [comment]
Not a bad idea will add in feature.

**Comment by krowinski** [comment]
done #9
