### ISSUE TITLE
bcmod 7.2 issue

### ISSUE THREAD

**Issue by krowinski** [krowinski/bcmath-extended#20]
As of 7.2 float can be passed to bcmod but they don't return correct values (IMO)

I created bug for this in https://bugs.php.net/bug.php?id=76287 but it was commented as documentation issue not a bug.

```
bcmod() doesn't use floor() but rather truncates towards zero,
which is also defined this way for POSIX fmod(), so that the
result always has the same sign as the dividend.  Therefore, this
is not a bug, but rather a documentation issue.
```

But I still will use floor not truncated for fmod in this lib.

**Comment by peter279k** [comment]
@krowinski, do you have any idea about this?
It looks like we have to do something for `bcomd` function in `php-7.2`.

**Comment by krowinski** [comment]
? I wrote this and its already fix in this lib its here just for info

**Comment by peter279k** [comment]
@krowinski, thank you for your reply. I've seen that. And this issue should be closed?

And add some info in `README.md`.

**Comment by krowinski** [comment]
added info in readme
