### ISSUE TITLE
Make getDecimalsLengthFromNumber() public

### ISSUE THREAD

**Issue by mbezhanov** [krowinski/bcmath-extended#21]
Is it possible to make `getDecimalsLengthFromNumber()` method `public` instead of `private`?

In an integration test of a project I'm working on, there's a case where I'd like to do:

```
$this->assertEquals(BC::round($expectedValue, BC::getDecimalsLengthFromNumber($actualValue), $actualValue);
```

I need to do this in that test, in order to ensure that a third-party system is returning properly rounded values. The inputs in the test are generated dynamically, and the third-party system outputs a varying number of decimals, depending on the size of the number.

Here are some example inputs and outputs to illustrate this:
 
```
--- Expected (inputs generated in the test)
+++ Actual (outputs returned from the third-party system)
@@ @@
-'1399454.22512577'
+'1399454.2251258'
-'959960482.27973165'
+'959960482.27973'
```

**Comment by krowinski** [comment]
Yes setting getDecimalsLengthFromNumber to public should not be a problem

**Comment by krowinski** [comment]
done
