### ISSUE TITLE
BC::pow only supports integer exponents

### ISSUE THREAD

**Issue by TheLevti** [krowinski/bcmath-extended#22]
> Please provide the following details.

Would it be possible to implement a bcmath function that can calculate `pow` with arbitrary precision, using a fractional exponent?

Maybe https://stackoverflow.com/questions/33486170/php-how-to-raise-number-to-tiny-fractional-exponent is a solution?

* *Operating System*: Linux
* *PHP Version*: 7.2.4

> Steps required to reproduce the problem.

1.  BC::pow('5', '0.05', 12)

> Expected Result.

Something like this.
`1.08379838673`

> Actual Result.

`The bcpow function only supports integer exponents. Try using pow instead.`

**Comment by TheLevti** [comment]
Thank you, you are a hero! :+1:

**Comment by krowinski** [comment]
np :) all changes in tag 4.0.0
