### ISSUE TITLE
Consider dropping support for php5 and php7.0

### ISSUE THREAD

**Issue by TheLevti** [krowinski/bcmath-extended#31]
Consider deprecating/dropping support for php 5.x and 7.0 in the next major version as they officially reached end of life some months ago. See: https://www.php.net/supported-versions.php

Why? Stay up to date & have all the nice things that php7.1+ offers.

> Please provide the following details.

* *Operating System*: any
* *PHP Version*: 5.x|7.0

> Steps required to reproduce the problem.

not required

> Expected Result.

not required

> Actual Result.

not required

**Comment by peter279k** [comment]
@TheLevti, thank you for your reply.

I agree with that.

**Comment by krowinski** [comment]
#32
