### ISSUE TITLE
Why is the trimming of trailing zeroes enforced by the functions?

### ISSUE THREAD

**Issue by ekr3peeK** [krowinski/bcmath-extended#36]
I can't understand why would you enforce the trimming of the trailing zeroes after the decimal point?

A global setting, or something simmilar, that can disable this would be nice. Additionally, the class is not extendable at all, as you are calling the static methods with the `self::` instead of the `static::` caller.

**Comment by krowinski** [comment]
I assume they are useless (as they usually are) and in my case scenario I din't need them. Sure can add as feature to disable this.

I prefer to use composition then class extending but sure this can be changed.

**Comment by ekr3peeK** [comment]
Thank you!:)

In my scenario, we are calculating with the same precision as we are displaying values in, and I prefer that all the numbers that are displayed be equally long, that's why it is useless for me:) Btw, this is a very nice little plugin, and it would have been a shame not using it.

**Comment by krowinski** [comment]
Changes in master is see one problem that not all bc function supports keeping zeros depends of version of php  😢   In future I will try to add addTRailingZeroFunction 😞

**Comment by krowinski** [comment]
ok I put few 🩹 🩹 🩹  on code and Its working I "love" to use if  php version > some number to keep this code working..

**Comment by krowinski** [comment]
tak 5.2.0 released
