### ISSUE TITLE
NULL handling is different from PHP's BCMath functions

### ISSUE THREAD

**Issue by gnutix** [krowinski/bcmath-extended#39]
> Please provide the following details.

* *Operating System*: Linux
* *PHP Version*: 7.2, 8.0

> Steps required to reproduce the problem.

1. Call BC::* with a null value

> Expected Result.

* Should work just like the BCMath functions

> Actual Result.

* `Fatal error: Uncaught TypeError: BCMathExtended\BC::*(): Argument #* ($*) must be of type string, null given`

See this demo with `bcadd` vs `BC::add`: https://phpsandbox.io/n/orange-snow-okeg-2feqa
And this Stackoverflow for explanation as to why this happens : https://stackoverflow.com/questions/45600400/php7-methods-with-a-scalar-type-declaration-refuse-to-type-juggle-null-values

PS: obviously, I don't call the lib with an explicit `null` on purpose ; it's the result of a very long chain of events in a big legacy project...

**Comment by krowinski** [comment]
Hi!

bcadd only accepts string as $left or $right https://www.php.net/manual/en/function.bcadd.php in your example you don't use 
declare(strict_types=1); so php just casts null to string thats why it's working. Lib use strict types.
I don't want to jiggle types and handle null. You can fork this and remove "declare(strict_types=1)" from lib this should have the same behavior.

https://phpsandbox.io/n/patient-disk-ekez-sxkgs

**Comment by gnutix** [comment]
Did you take a look at my PR ? I would much rather not have to maintain a separate package, especially for such a change that doesn't seem so extreme in philosophy.

But in the meantime, I've created a fork like you suggested, so here it is : https://packagist.org/packages/gammadia/bcmath-extended-nullable

**Comment by TheLevti** [comment]
Its makes no sense to support NULL for any of those relevant functions. Don't call the method if the value is null.

**Comment by gnutix** [comment]
Then I guess if that's how you feel about it, that's how it'll be. I'll keep the fork, as I do need to have that null accepted and handled like it did on PHP 7.x.

PS : https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg
