### ISSUE TITLE
roundHalfEven working incorrectly?

### ISSUE THREAD

**Issue by linas-b** [krowinski/bcmath-extended#41]
> Please provide the following details.

* *Operating System*: Linux
* *PHP Version*: 8.0

> Steps required to reproduce the problem.

```
$value = '1.1259';
$scale = 2;
var_dump(round($value, $scale, PHP_ROUND_HALF_EVEN)); // float(1.13)
var_dump(BC::roundHalfEven($value, $scale)); // string(4) "1.12"
```

> Expected Result.

* Should be '1.13'? Right?

> Actual Result.

* `string(4) "1.12"`

**Comment by krowinski** [comment]
indeed in this scenario it was returning invalid values fix in 6.0.1 tag
