### ISSUE TITLE
using hexdec on PHP 7.4 logs: "PHP Deprecated:  Invalid characters passed for attempted conversion"

### ISSUE THREAD

**Issue by arvilmena** [krowinski/bcmath-extended#42]
> Please provide the following details.

* *Operating System*: Linux and OS X
* *PHP Version*: 7.4

> Steps required to reproduce the problem.

1. Use `hexdec` method, for example: `BC::hexdec('0x300000000d2c12440c4310c20c2428c20c8330cc0ca318ca0cc330cc0c230806')`

> Expected Result.

* Ideally no warnings

> Actual Result.

```PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in /<path>/vendor/krowinski/bcmath-extended/src/BCMathExtended/BC.php on line 438```

Currently using version `6.0.0`

**Comment by krowinski** [comment]
"0x" was causing depreciation warnings that was added in php 7.4 when invalid data is passed to hexdec.

I fixed this issue in 6.0.1
